const axios = require('axios')
const fs = require('fs')
const path = require('path')
const LRU = require('lru-cache')
const express = require('express')
const session = require('express-session');
const compression = require('compression')
const microcache = require('route-cache')
const cors = require('cors');
const resolve = file => path.resolve(__dirname, file)
const {createBundleRenderer} = require('vue-server-renderer')

const isProd = process.env.NODE_ENV === 'production'
const useMicroCache = process.env.MICRO_CACHE !== 'false'
const serverInfo =
    `express/${require('express/package.json').version} ` +
    `vue-server-renderer/${require('vue-server-renderer/package.json').version}`

const app = express();
app.use(cors({origin: 'http://seltrans.ru'}));

app.use(session({
    secret: '241h24bqmwndbasmda;sda;s,dcmz,xmncj.bj12jebJAsdha<HASGDAHsgdhj1,2',
    resave: false,
    saveUninitialized: true
}));

const nodemailer = require('nodemailer');

const bodyParser = require('body-parser');
app.use(bodyParser.urlencoded({limit: '10mb', extended: true}));
app.use(bodyParser.json({limit: '10mb', extended: true}));

let multer = require('multer');
let upload = multer({dest: 'uploads/'});
// app.use(upload.array());

const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: 'siteinformingservice@gmail.com',
        pass: 'xftywqtydjouxmtl'
    }
});

let device = require('express-device');
app.use(device.capture());

function createRenderer(bundle, options) {
    return createBundleRenderer(bundle, Object.assign(options, {
        cache: LRU({
            max: 1000,
            maxAge: 1000 * 60 * 15
        }),
        basedir: resolve('./dist'),
        runInNewContext: false
    }))
}

let renderer
let readyPromise
const templatePath = resolve('./src/index.template.html')
if (isProd) {
    // In production: create server renderer using template and built server bundle.
    // The server bundle is generated by vue-ssr-webpack-plugin.
    const template = fs.readFileSync(templatePath, 'utf-8')
    const bundle = require('./dist/vue-ssr-server-bundle.json')
    // The client manifests are optional, but it allows the renderer
    // to automatically infer preload/prefetch links and directly add <script>
    // tags for any async chunks used during render, avoiding waterfall requests.
    const clientManifest = require('./dist/vue-ssr-client-manifest.json')
    renderer = createRenderer(bundle, {
        template,
        clientManifest
    })
} else {
    // In development: setup the dev server with watch and hot-reload,
    // and create a new renderer on bundle / index template update.
    readyPromise = require('./build/setup-dev-server')(
        app,
        templatePath,
        (bundle, options) => {
            renderer = createRenderer(bundle, options)
        }
    )
}

const serve = (path, cache) => express.static(resolve(path), {
    maxAge: cache && isProd ? 1000 * 60 * 60 * 24 * 30 : 0
})

app.use(compression({threshold: 0}))
app.use('/.well-known/pki-validation/212EA93F4983B611C84BFD9ED9C23DCD.txt', serve('./public/.well-known/pki-validation/212EA93F4983B611C84BFD9ED9C23DCD.txt', true))
app.use('/dist', serve('./dist', true))
app.use('/public', serve('./public', true))
app.use('/manifest.json', serve('./manifest.json', true))
app.use('/service-worker.js', serve('./dist/service-worker.js'))
app.use('/css', serve('./public/css', true));
app.use('/fonts', serve('./public/fonts', true));
app.use('/content', serve('./content', true));
app.use('/robots.txt', serve('./public/robots.txt', true));
app.use('/mailru-domainbOGaPuznsXompOOB.html', serve('./public/mailru-domainbOGaPuznsXompOOB.html', true));
app.use('/google92f2715ac9fa288e.html', serve('./public/google92f2715ac9fa288e.html', true));
app.use('/sitemap.xml', serve('./public/sitemap.xml', true));
app.use('/img', serve('./public/img', true));
app.use('/share', serve('./public/share', true));
app.use('/favicon', serve('./public/favicon', true));
app.use('/video', serve('./public/video', true));
app.use(microcache.cacheSeconds(1, req => useMicroCache && req.originalUrl))

function render(req, res) {
    if (req.path.substr(-1) === '/' && req.path.length > 1) {
        let query = req.url.slice(req.path.length);
        res.redirect(301, req.path.slice(0, -1) + query);
        return;
    }

    let browser = 'other';
    const context = {
        title: req.url.indexOf('/en') !== -1 ? 'S-Electrotransport' : 'С-Электротранспорт',
        device: req.device.type.toLowerCase(),
        url: req.url,
        meta: '',
        browser: browser,
        language: req.url.indexOf('/en') !== -1 ? 'en' : 'ru'
    };

    let s = Date.now()
    res.setHeader("Content-Type", "text/html")
    res.setHeader("Server", serverInfo)
    const handleError = err => {
        if (err.url) {
            res.redirect(err.url)
        } else if (err.code === 404) {
            // res.status(404).send('404 | Page Not Found')
            res.status(404).sendFile(path.join(__dirname + '/content/404' + context.language + '.html'));
        } else {
            // const mailOptions = {
            //     from: 'Ошибка 500 Biopack <siteinformingservice@gmail.com>',
            //     to: 'caspanch@gmail.com',
            //     subject: 'Ошибка 500 Biopack',
            //     html: err.stack + ' URL:' + req.url
            // };
            //
            // transporter.sendMail(mailOptions, function (err, info) {
            //
            // });
            res.status(500).send('500 | Internal Server Error')
            console.error(`error during render : ${req.url}`)
            console.error(err.stack)
        }
    };

    renderer.renderToString(context, (err, html) => {
        if (err) {
            return handleError(err)
        }

        if (context.state.route.name === '404' || context.state.route.name === '404En') {
            res.status(404).send(html)
            return;
        }

        res.send(html);
        if (!isProd) {
            console.log(`whole request: ${Date.now() - s}ms`)
        }
    })
}

app.post('/send-form-recall', function (req, res) {
    let mailOptions = {
        from: 'Обратный звонок <siteinformingservice@gmail.com>',
        to: 'caspanch@gmail.com',
        subject: 'Обратный звонок Софрино',
        html: '<p>Обратный звонок Софрино</p><p>Имя: ' + req.body.name + '</p><p>Телефон: ' + req.body.phone + '</p>'
    };

    transporter.sendMail(mailOptions, function (err, info) {
        if (err) {
            // console.log(err)
        } else {
            console.log('email sended')
        }
    });
    
    mailOptions.to = 'info@seltrans.ru';
    transporter.sendMail(mailOptions, function (err, info) {
        if (err) {
            // console.log(err)
        } else {
            console.log('email sended')
            // console.log(info);
        }
    });

    res.status(200).end(JSON.stringify({status: 'ok'}));
});

app.post('/send-form-question', function (req, res) {
    let mailOptions = {
        from: 'Вопрос <siteinformingservice@gmail.com>',
        to: 'caspanch@gmail.com',
        subject: 'Вопрос Софрино',
        html: '<p>Вопрос Софрино</p><p>Имя: ' + req.body.name + '</p><p>Телефон: ' + req.body.phone + '</p><p>Email:' + req.body.email + '</p><p>Message:' + req.body.message + '</p>'
    };

    transporter.sendMail(mailOptions, function (err, info) {
        if (err) {
            // console.log(err)
        } else {
            console.log('email sended')
        }
    });
    
    mailOptions.to = 'info@seltrans.ru';
    transporter.sendMail(mailOptions, function (err, info) {
        if (err) {
            // console.log(err)
        } else {
            console.log('email sended')
            // console.log(info);
        }
    });

    res.status(200).end(JSON.stringify({status: 'ok'}));
});

app.post('/send-form-order', function (req, res) {
    let mailOptions = {
        from: 'Расчет стоимости <siteinformingservice@gmail.com>',
        to: 'caspanch@gmail.com',
        subject: 'Расчет стоимости Софрино',
        html: '<p>Расчет стоимости Софрино</p><p>Имя: ' + req.body.name + '</p><p>Телефон: ' + req.body.phone + '</p><p>Сообщение: ' + req.body.message + '</p>'
    };

    if(req.body.file !== '') {
        mailOptions.attachments = {
            path: req.body.file
        };
    }

    transporter.sendMail(mailOptions, function (err, info) {
        if (err) {
            console.log(err)
        } else {
            // console.log('email sended')
        }
    });
    
    mailOptions.to = 'info@seltrans.ru';
    transporter.sendMail(mailOptions, function (err, info) {
        if (err) {
            // console.log(err)
        } else {
            console.log('email sended')
            // console.log(info);
        }
    });

    res.status(200).end(JSON.stringify({status: 'ok'}));
});

app.get('/admin-page', (req, res) => {
    // let currentPath = req.protocol + '://' + req.headers['x-forwarded-host'] + req.originalUrl;
    if (req.headers['x-forwarded-host'] === 'edit-seltrans.burno.tech') {
        res.status(200).sendFile(path.join(__dirname + '/content/auth.html'));
    } else {
        res.status(404).send('NOT FOUND');
    }

});

app.post('/auth', (req, res) => {
    let login = req.body.login,
        password = req.body.password;
    if (login === 'seltranse-login' && password === 'asd1asd2;1;as<>n1,2n3.,asdnxc' && req.headers['x-forwarded-host'] === 'edit-seltrans.burno.tech') {
        req.session.auth = true;
    }
    res.redirect(302, '/');
});

app.post('/authStatus', (req, res) => {
    let status = false;
    if (req.session.auth === true && req.headers['x-forwarded-host'] === 'edit-seltrans.burno.tech') {
        status = true;
    }
    res.status(200).end(JSON.stringify({status: status}));
});

app.get('*', isProd ? render : (req, res) => {
    // console.log(req.session.auth);
    readyPromise.then(() => render(req, res))
});

let apiUrl = 'http://api.burno.tech',
    email = 'vb@burno.tech',
    password = "asdm2m12gjkjadsfp1o;\\'asdaslmfcnbavr1jmgcgedadbans,,,NASda";

function checkUserAuth(req) {
    return (req.session.auth === true && req.headers['x-forwarded-host'] === 'edit-seltrans.burno.tech');
}

app.post('/api/addArticlePhoto', upload.single('file'), (req, res) => {
    if (checkUserAuth(req)) {
        axios({
            method: 'POST',
            url: apiUrl + '/api/moveArticlePhoto',
            data: {
                email: email,
                password: password,
                filename: req.file.filename,
                originalname: req.file.originalname,
                key: req.body.key,
                url: req.body.url,
                page: req.body.page,
                galleryKey: req.body.galleryKey
            }
        })
            .then(function (response) {
                // console.log(response.data)
            })
            .catch(function (error) {
                // console.log(error)
            });

        res.status(200).end(JSON.stringify({status: 'ok'}));
    }
});

app.post('/api/*', (req, res) => {
    if (checkUserAuth(req)) {
        let url = req.path.split('/');
        url = url[2];
        switch (url) {
            case 'editJson':
                axios({
                    method: 'POST',
                    url: apiUrl + '/api/editJson',
                    data: {
                        email: email,
                        password: password,
                        value: req.body.value,
                        language: req.body.language,
                        page: req.body.page,
                        key: req.body.key
                    }
                })
                    .then((response) => {
                    })
                    .catch(function (error) {

                    });
                break;
            case 'editArticleJson':
                axios({
                    method: 'POST',
                    url: apiUrl + '/api/editArticleJson',
                    data: {
                        email: email,
                        password: password,
                        value: req.body.value,
                        language: req.body.language,
                        page: req.body.page,
                        url: req.body.url,
                        key: req.body.key
                    }
                })
                    .then((response) => {
                        // console.log(response.data)
                    })
                    .catch(function (error) {

                    });
                break;
            case 'editConstantJson':
                axios({
                    method: 'POST',
                    url: apiUrl + '/api/editConstantJson',
                    data: {
                        email: email,
                        password: password,
                        value: req.body.value,
                        language: req.body.language,
                        page: req.body.page,
                        key: req.body.key
                    }
                })
                    .then(function (response) {
                        // console.log(response.data)
                    })
                    .catch(function (error) {
                        // console.log(error)
                    });
                break;
        }
    }
    res.status(200).end(JSON.stringify({status: 'ok'}));
});

const port = process.env.PORT || 4040;

if(process.env.NODE_ENV === 'test') {
    module.exports = app;
} else {
    app.listen(port, () => {
        console.log(`server started at localhost:${port}`)
    })
}